validators: 10
operatorIDs: [143, 219, 33, 34]
withdrawAddress: "0xa1a66cc5d309f19fb2fda2b7601b223053d0f7f4"
owner: "0xb64923DA2c1A9907AdC63617d882D824033a091c"
nonce: 0
network: "holesky"
operatorsInfo: '[{"id":143,"public_key":"LS0tLS1...RSA...","ip":"https://141.94.143.182:3030"},{"id":219,"public_key":"LS0tLS1...RSA...","ip":"https://209.35.77.243:12015"}]'
outputPath: /data/output
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/debug.log



validators: 10 # amount of validators to generate (nonce incrementing by 1) (default: 1)
operatorIDs: [143, 219, 33, 34] # array of Operator IDs which will be used for a DKG ceremony
withdrawAddress: "0xa1a66cc5d309f19fb2fda2b7601b223053d0f7f4" # address where reward payments for the validator are sent
owner: "0xb64923DA2c1A9907AdC63617d882D824033a091c" # address of owner of the Cluster that will manage the validator on ssv.network
nonce: 0 # owner nonce for the SSV contract (default: 0)
network: "holesky" # network name (default: mainnet)
operatorsInfo: '[{"id": 1,"public_key": "LS0tLS1CRUdJTiBSU0....","ip": "https://localhost:3030"}, {"id": 2,"public_key": "LS0tLS1CRUdJTiBSU0....","ip": "http://localhost:3030"},...]' # raw content of the JSON file with operators information
# Alternatively:
# operatorsInfoPath: /data/initiator/operators_info.json
outputPath: /data/output #  path to store the resulting staking deposit and ssv contract payload files
logLevel: info # logger's log level (default: debug)
logFormat: json # logger's encoding (default: json)
logLevelFormat: capitalColor # logger's level format (default: capitalColor)
logFilePath: /data/debug.log # path to file where logs should be written (default: ./data/debug.log)